In [ ]:

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATASETS
# TO THE CORRECT LOCATION (/kaggle/input) IN YOUR NOTEBOOK,
# THEN FEEL FREE TO DELETE CELL.

import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote
from urllib.error import HTTPError
from zipfile import ZipFile

CHUNK_SIZE = 40960
DATASET_MAPPING = 'home-data-for-ml-course:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-competitions-data%2Fkaggle-v2%2F10211%2F111096%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20210804%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20210804T101151Z%26X-Goog-Expires%3D259199%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D664825e7268a2cd11e95bd113f7c409b97e39fdf20a2e42ffc6798596e8f4390dfc4f6c5ba8adfbfd8f8a73832f9889bc3c4c03fa7d21014126b1f9697ff1818bfee7bac85262b39625b820905a6a885d96750e1aef08852bf4c5ca5881575e96e0056df09d3b665fe491e1577d701105d6cdc8d26223852fe648df2e44befc08b92cc4d076f2d51ab848d7656308fe895b69c4671024ac1279fa94d7d2c849abc68bf32ad81609d2233406594e53b6a7a64a023653b7ce2c961eee283072022d37779f22cfd0b8573e494ff5e8a46dad73efe86d321fdb2f1fe139711f734bc8b6666050f2324e887e59773c6f74413c666c3a7af675de12b70bb101c440756,mobile-price-classification:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F11167%2F15520%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20210804%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20210804T101151Z%26X-Goog-Expires%3D259199%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D5e12bc25419c8edac9ca4f451c7723ea4f2410612e87efb3dda85c5e6329f37d948e0821db09fdf752a45a3a05b2284cb805798ef54b81e52dbc0a08a68c6bcc6f01a14488050f0225facefea92b0b42ac1112aae89e274b2719389094742bc4a9233a0a0355c5c6618de85f2c348a0c07adcd6e1718b4e5bc63dd83294dbe094fc54166a64c3d0619ff5f0fd4acc93ab490677cfdc7f9cfae0e7e5c09237ffad1037e70b1c3a7b315ee57f51c618775930e92c5e337a1b832ca5b7c7acfab3bf75c3ddb3bfd2d2f6b3e8a4c8e0a634e05b97b4f8cca7d62163071dc3ab85f86eb64f00ef675e55d7a6c3048f255793503db6fe1c383fde0de16536bf8560751,melbourne-housing-snapshot:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F2709%2F38454%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20210804%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20210804T101151Z%26X-Goog-Expires%3D259199%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D5477db2a3f22e4f3284caa19ebdb27289592d60389778eaaa3b1f1a7ccfe8006701a2bc9f8903937dfd1eb4fa725ec52f67f275cc6618070eb9a486b2f51a41c80536bb8d98959fa62a9e4637952b5f1d711aa3711b61f71caa01071a12971792e182d76a1fb166a195bd333421ebfb366bb44fc98eeac7e5d8e66630d8821fcde989ba370f2c400c9fdcf76ebe2e0a5126359effdebb9c31c0d52aaf35a0446c4f7dd0468ccd92d882c78983f1459dfc6822bc34ace2881e8e75d75cc71eceed7034372ccbf5be0a021442665c2acba8bda84ecae2c29ce6fd7180ca930f2f758a15d4f9f09fb3150cd8ededb1ff88b0757127e850b57efd05323f7403044de'
KAGGLE_INPUT_PATH='/home/kaggle/input'
KAGGLE_INPUT_SYMLINK='/kaggle'

os.makedirs(KAGGLE_INPUT_PATH, 777)
os.symlink(KAGGLE_INPUT_PATH, os.path.join('..', 'input'), target_is_directory=True)
os.makedirs(KAGGLE_INPUT_SYMLINK)
os.symlink(KAGGLE_INPUT_PATH, os.path.join(KAGGLE_INPUT_SYMLINK, 'input'), target_is_directory=True)

for dataset_mapping in DATASET_MAPPING.split(','):
    directory, download_url_encoded = dataset_mapping.split(':')
    download_url = unquote(download_url_encoded)
    destination_path = os.path.join(KAGGLE_INPUT_PATH, directory)
    try:
        with urlopen(download_url) as zipfileres, NamedTemporaryFile() as tfile:
            total_length = zipfileres.headers['content-length']
            print(f'Downloading {directory}, {total_length} bytes zipped')
            dl = 0
            data = zipfileres.read(CHUNK_SIZE)
            while len(data) > 0:
                dl += len(data)
                tfile.write(data)
                done = int(50 * dl / int(total_length))
                sys.stdout.write(f"\r[{'=' * done}{' ' * (50-done)}] {dl} bytes downloaded")
                sys.stdout.flush()
                data = zipfileres.read(CHUNK_SIZE)
            print(f'\nUnzipping {directory}')
            with ZipFile(tfile) as zfile:
                zfile.extractall(destination_path)
    except HTTPError as e:
        print(f'Failed to load (likely expired) {download_url} to path {destination_path}')
        continue
    except OSError as e:
        print(f'Failed to load {download_url} to path {destination_path}')
        continue
print('Dataset import complete.')

# Using Pandas to Get Familiar With Your Data

The first step in any machine learning project is familiarize yourself with the data.  You'll use the Pandas library for this.  Pandas is the primary tool data scientists use for exploring and manipulating data.  Most people abbreviate pandas in their code as `pd`.  We do this with the command

In [1]:
import pandas as pd

The most important part of the Pandas library is the DataFrame.  A DataFrame holds the type of data you might think of as a table. This is similar to a sheet in Excel, or a table in a SQL database. 

Pandas has powerful methods for most things you'll want to do with this type of data.  

As an example, we'll look at [data about home prices](https://www.kaggle.com/dansbecker/melbourne-housing-snapshot) in Melbourne, Australia. In the hands-on exercises, you will apply the same processes to a new dataset, which has home prices in Iowa.

The example (Melbourne) data is at the file path **`../input/melbourne-housing-snapshot/melb_data.csv`**.

We load and explore the data with the following commands:

In [4]:
# save filepath to variable for easier access
melbourne_file_path = '/kaggle/input/melbourne-housing-snapshot/melb_data.csv'
# read the data and store data in DataFrame titled melbourne_data
melbourne_data = pd.read_csv(melbourne_file_path) 
# print a summary of the data in Melbourne data
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

# Interpreting Data Description
The results show 8 numbers for each column in your original dataset. The first number, the **count**,  shows how many rows have non-missing values.  

Missing values arise for many reasons. For example, the size of the 2nd bedroom wouldn't be collected when surveying a 1 bedroom house. We'll come back to the topic of missing data.

The second value is the **mean**, which is the average.  Under that, **std** is the standard deviation, which measures how numerically spread out the values are.

To interpret the **min**, **25%**, **50%**, **75%** and **max** values, imagine sorting each column from lowest to highest value.  The first (smallest) value is the min.  If you go a quarter way through the list, you'll find a number that is bigger than 25% of the values and smaller than 75% of the values.  That is the **25%** value (pronounced "25th percentile").  The 50th and 75th percentiles are defined analogously, and the **max** is the largest number.


# Your Turn
Get started with your **[first coding exercise](https://www.kaggle.com/kernels/fork/1258954)**

---




*Have questions or comments? Visit the [Learn Discussion forum](https://www.kaggle.com/learn-forum/161285) to chat with other Learners.*